language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy
    - pypy3
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade -r requirements.txt
    - pip install tox
    - pip install mock
    - pip install importlib
    - pip install coverage
    - pip install coveralls
script:
    - coverage run --source=mongorest test.py
after_success:
    - coveralls
