language: python
services:
  - mongodb
install:
  - pip install tox
before_script:
  - sleep 15
  - mongo mongorest --eval 'db.addUser("mongorest", "mongorest");'
script:
  - tox
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3