language: python
python:
  - "3.5"
services:
  - mongodb
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install tox coverage coveralls
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
before_script:
  - sleep 10
  - mongo mongorest --eval 'db.addUser("mongorest", "mongorest");'
script:
  - tox -r
after_success:
  - coveralls
