language: python
python:
    - py26
    - py27
    - py33
    - py34
    - pypy
    - pypy3
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade -r requirements.txt
    - pip install --ugprade tox mock coverage coveralls
script:
    - coverage run --source=mongorest tests.py
after_success:
    coveralls
