language: python
python:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade -r requirements.txt
    - pip install --ugprade tox
    - pip install --upgrade coverage
    - pip install --ugprade coveralls"
script:
    - coverage run --source=mongorest setup.py test
after_success:
    coveralls
